# Where is the Triangle?

In [69]:
n = 100
E = 2
A = np.zeros((n, n))
for _ in range(E):
    i = random.randint(0, n-1)
    j = random.randint(0, n-1)
    while i == j:
        j = random.randint(0, n-1)
    A[i][j] = 1
print(A)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [70]:
# Not so smart way

import numpy as np
import random

# n = 4
# vertices = np.arange(n)

# define adjacency matrix
# A = np.array([[random.randint(0,1) for _ in range(n)] for _ in range(n)])

# A = np.array([[0, 1, 0, 0],
#               [1, 0, 1, 1],
#               [0, 1, 0, 1],
#               [0, 1, 1, 0]])

# set diagonal 0
for i in range(n): A[i][i] = 0

print(A)

# check for diagonal, one vertex at a time
@timeit
def has_triangle(X):
    dim = len(X[0])
    for n in range(dim):
        for i in range(dim):
            if X[n][i] == 1:
                for j in range(dim):
                    if X[i][j] == 1 and j != n:
                        if X[n][j] == 1:
                            print("There is a triangle between points {}, {}, and {}.".format(n+1, i+1, j+1))
                            return None
    else:
        print("There is no triangle.")
            
has_triangle(A)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
There is no triangle.
'has_triangle'  9.90 ms


In [71]:
# Faster, smart way

import numpy as np
import random

# n = 4
# vertices = np.arange(n)

# define adjacency matrix
# A = np.array([[random.randint(0,1) for _ in range(n)] for _ in range(n)])

# A = np.array([[0, 1, 0, 0],
#               [1, 0, 1, 1],
#               [0, 1, 0, 1],
#               [0, 1, 1, 0]])

# set diagonal 0
for i in range(n): A[i][i] = 0

print(A)

# check existence with linear algebra
@timeit
def has_triangle(X):
    dim = len(X[0])
    
    # calculate X^2
    B = X.dot(X)

    # check if both A[i][j] and B[i][j] are non zero
    for i in range(dim):
        for j in range(dim):
            if B[i][j] == 1 and X[i][j] == 1:
                print("There is a triangle.")
                return None
    else:
        print("There is not a triangle.")

has_triangle(A)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
There is not a triangle.
'has_triangle'  124.25 ms


In [46]:
# don't worry about this

import time

def timeit(method):
    def timed(*args, **kw):
        ts = time.time()
        result = method(*args, **kw)
        te = time.time()
        if 'log_time' in kw:
            name = kw.get('log_name', method.__name__.upper())
            kw['log_time'][name] = int((te - ts) * 1000)
        else:
            print ('%r  %2.2f ms' % \
                  (method.__name__, (te - ts) * 1000))
        return result
    return timed